default:
  image: registry.gitlab.com/speedodevo/skaffold:v1.5.0

  services:
    - docker:19.03.8-dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export KUBECONFIG=$KUBECONFIG_OKTETO
    - kubectl config current-context

variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - deploy

skaffold:
  stage: deploy
  script:
    - skaffold run
