default:
  image: registry.gitlab.com/speedodevo/skaffold:v0.0.1

  services:
    - docker:18.09.6-dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export KUBECONFIG=$KUBECONFIG_OKTETO
    - echo "$KUBECONFIG"
    - kubectl config current-context

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - deploy

skaffold:
  stage: deploy
  script:
    - skaffold run
