apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.gitlab.com/speedodevo/todo-app
      context: src/todo-service
deploy:
  helm:
    releases:
      - name: skaffold-todo-app
        chartPath: deploy/helm
        values:
          todo-service.image: registry.gitlab.com/speedodevo/todo-app
