apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-web-ui.fullname" . }}
spec:
  type: {{ .Values.serviceType }}
  selector:
{{ include "todo-web-ui.labels" . | indent 4 }}
  ports:
    - port: 80
