apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "todo-service.fullname" . }}
  labels:
{{ include "todo-service.labels" . | indent 4 }}
data:
  POSTGRES_HOST: "{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}"
  POSTGRES_PORT: "{{ .Values.postgresql.service.port }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
  POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
