apiVersion: v1
kind: Secret
metadata:
  name: {{ template "todo-service.fullname" . }}
  labels:
{{ include "todo-service.labels" . | indent 4 }}
type: Opaque
data:
  TOKEN_KEY: "{{ required "todo-service.tokenKey is required" .Values.tokenKey | b64enc }}"
  POSTGRES_PASSWORD: "{{ required "todo-service.postgresql.postgresqlPassword is required" .Values.postgresql.postgresqlPassword | b64enc }}"
