apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-service.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: {{ .Values.serviceType }}
  selector:
{{ include "todo-service.labels" . | indent 4 }}
  ports:
    - port: 80
