apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-service.fullname" . }}
spec:
  type: LoadBalancer
  selector:
{{ include "todo-service.pod-labels" . | indent 4 }}
  ports:
    - port: 80
